# Generated by Django 4.2.2 on 2023-06-30 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_profile_instagram_url_profile_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='instagram_url',
        ),
    ]
