# Generated by Django 4.2.2 on 2023-07-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0013_alter_comment_options_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='name_users',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
