# Generated by Django 4.2.2 on 2023-07-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0015_followerscount_alter_category_name_alter_post_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesOfArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа статьи')),
            ],
            options={
                'verbose_name': 'Тип статьи',
                'verbose_name_plural': 'Типы статей',
            },
        ),
        migrations.DeleteModel(
            name='FollowersCount',
        ),
        migrations.AddField(
            model_name='post',
            name='type_of_articles',
            field=models.CharField(default='type', max_length=255, verbose_name='Тип статьи'),
        ),
    ]
