# Generated by Django 4.2.2 on 2023-07-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0016_typesofarticles_delete_followerscount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type_of_articles',
            field=models.CharField(max_length=255, verbose_name='Тип статьи'),
        ),
    ]
