# Generated by Django 4.2.7 on 2023-11-24 14:01

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theblog', '0017_alter_post_type_of_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPost',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('header_image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Изображение')),
                ('title_tag', models.CharField(max_length=255, verbose_name='Тег названия')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('post_date', models.DateField(blank=True, editable=False)),
                ('category', models.CharField(default='coding', max_length=255, verbose_name='Категория')),
                ('snippet', models.CharField(max_length=255, verbose_name='Сниппет')),
                ('type_of_articles', models.CharField(max_length=255, verbose_name='Тип статьи')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Запись',
                'verbose_name_plural': 'historical Записи',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
